# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1.xci
# IP: The module: 'LMAC_ETH_1G_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LMAC_ETH_1G_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'LMAC_ETH_1G_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'LMAC_ETH_1G_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1.xci
# IP: The module: 'LMAC_ETH_1G_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LMAC_ETH_1G_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'LMAC_ETH_1G_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'LMAC_ETH_1G_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
