webtalk_init -webtalk_dir /home/lewiz2/lewiz2-sambashare/KIRATEY/LMAC_ETH_1G_NEW_BRIDGE/AXIS_LMAC_IP/AXIS_LMAC_IP.sim/sim_1/behav/xsim/xsim.dir/LMAC_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr  8 15:31:36 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "56ed89b2-5f39-495d-a73b-b33ed1c265d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d8674e12df7c4debb99ff44094a30793" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "61" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3301.907 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 fs" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "138244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3876503275 -regid "211002456_1777503594_210664227_309" -xml /home/lewiz2/lewiz2-sambashare/KIRATEY/LMAC_ETH_1G_NEW_BRIDGE/AXIS_LMAC_IP/AXIS_LMAC_IP.sim/sim_1/behav/xsim/xsim.dir/LMAC_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/lewiz2/lewiz2-sambashare/KIRATEY/LMAC_ETH_1G_NEW_BRIDGE/AXIS_LMAC_IP/AXIS_LMAC_IP.sim/sim_1/behav/xsim/xsim.dir/LMAC_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/lewiz2/lewiz2-sambashare/KIRATEY/LMAC_ETH_1G_NEW_BRIDGE/AXIS_LMAC_IP/AXIS_LMAC_IP.sim/sim_1/behav/xsim/xsim.dir/LMAC_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
