# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xci
# IP: The module: 'br_sfifo_ip_4x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'br_sfifo_ip_4x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'br_sfifo_ip_4x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xci
# IP: The module: 'br_sfifo_ip_4x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'br_sfifo_ip_4x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'br_sfifo_ip_4x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
