# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC1_INTEGRATED/LMAC_ETH_1G/CONSTRAINTS/LMAC_ETH_1G.xdc

# Block Designs: bd/LMAC_ETH_1G/LMAC_ETH_1G.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G || ORIG_REF_NAME==LMAC_ETH_1G} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_zynq_ultra_ps_e_0_0/LMAC_ETH_1G_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_axi_dma_0_1 || ORIG_REF_NAME==LMAC_ETH_1G_axi_dma_0_1} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/LMAC_ETH_1G_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_axi_smc_1 || ORIG_REF_NAME==LMAC_ETH_1G_axi_smc_1} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_rst_ps8_0_49M_1/LMAC_ETH_1G_rst_ps8_0_49M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_rst_ps8_0_49M_1 || ORIG_REF_NAME==LMAC_ETH_1G_rst_ps8_0_49M_1} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ps8_0_axi_periph_1/LMAC_ETH_1G_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_ps8_0_axi_periph_1 || ORIG_REF_NAME==LMAC_ETH_1G_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/LMAC_ETH_1G_AXIS_LMAC_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_AXIS_LMAC_IP_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_AXIS_LMAC_IP_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_0_0/LMAC_ETH_1G_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconstant_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconstant_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_c_counter_binary_0_0/LMAC_ETH_1G_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_c_counter_binary_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_0_0/LMAC_ETH_1G_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlslice_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlslice_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_0_0/LMAC_ETH_1G_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_ila_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_ila_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_0_0/LMAC_ETH_1G_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_util_ds_buf_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_1_0/LMAC_ETH_1G_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_util_ds_buf_1_0 || ORIG_REF_NAME==LMAC_ETH_1G_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_c_counter_binary_1_0/LMAC_ETH_1G_c_counter_binary_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_c_counter_binary_1_0 || ORIG_REF_NAME==LMAC_ETH_1G_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_1_0/LMAC_ETH_1G_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlslice_1_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlslice_1_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_2_0/LMAC_ETH_1G_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlslice_2_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlslice_2_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_3_0/LMAC_ETH_1G_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlslice_3_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlslice_3_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconcat_0_0/LMAC_ETH_1G_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconcat_0_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconcat_0_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_1_0/LMAC_ETH_1G_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconstant_1_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconstant_1_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_2_0/LMAC_ETH_1G_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconstant_2_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconstant_2_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_3_0/LMAC_ETH_1G_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconstant_3_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconstant_3_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_4_0/LMAC_ETH_1G_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconstant_4_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconstant_4_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_5_0/LMAC_ETH_1G_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_xlconstant_5_0 || ORIG_REF_NAME==LMAC_ETH_1G_xlconstant_5_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_1_0/LMAC_ETH_1G_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_ila_1_0 || ORIG_REF_NAME==LMAC_ETH_1G_ila_1_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_2_0/LMAC_ETH_1G_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_ila_2_0 || ORIG_REF_NAME==LMAC_ETH_1G_ila_2_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_3_0/LMAC_ETH_1G_ila_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_ila_3_0 || ORIG_REF_NAME==LMAC_ETH_1G_ila_3_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_ds_0/LMAC_ETH_1G_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_auto_ds_0 || ORIG_REF_NAME==LMAC_ETH_1G_auto_ds_0} -quiet] -quiet

# IP: bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_pc_0/LMAC_ETH_1G_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LMAC_ETH_1G_auto_pc_0 || ORIG_REF_NAME==LMAC_ETH_1G_auto_pc_0} -quiet] -quiet

# XDC: bd/LMAC_ETH_1G/LMAC_ETH_1G_ooc.xdc
