# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu15eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.cache/wt [current_project]
set_property parent.project_path /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/AXIS_LMAC_IP [current_project]
set_property ip_output_repo /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/hdl/LMAC_ETH_1G_wrapper.v
add_files /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/LMAC_ETH_1G.bd
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_zynq_ultra_ps_e_0_0/LMAC_ETH_1G_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_zynq_ultra_ps_e_0_0/LMAC_ETH_1G_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/LMAC_ETH_1G_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_10/bd_b2d9_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_19/bd_b2d9_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_25/bd_b2d9_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_29/bd_b2d9_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_30/bd_b2d9_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_31/bd_b2d9_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_32/bd_b2d9_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_33/bd_b2d9_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_34/bd_b2d9_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_26/bd_b2d9_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_27/bd_b2d9_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_28/bd_b2d9_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_20/bd_b2d9_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_21/bd_b2d9_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_11/bd_b2d9_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_12/bd_b2d9_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_13/bd_b2d9_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_14/bd_b2d9_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_15/bd_b2d9_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_2/bd_b2d9_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_3/bd_b2d9_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_4/bd_b2d9_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_5/bd_b2d9_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_6/bd_b2d9_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_1/bd_b2d9_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_1/bd_b2d9_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_rst_ps8_0_49M_1/LMAC_ETH_1G_rst_ps8_0_49M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_rst_ps8_0_49M_1/LMAC_ETH_1G_rst_ps8_0_49M_1.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_rst_ps8_0_49M_1/LMAC_ETH_1G_rst_ps8_0_49M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_c_counter_binary_0_0/LMAC_ETH_1G_c_counter_binary_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_0_0/LMAC_ETH_1G_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_0_0/LMAC_ETH_1G_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_0_0/LMAC_ETH_1G_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_0_0/LMAC_ETH_1G_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_1_0/LMAC_ETH_1G_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_1_0/LMAC_ETH_1G_util_ds_buf_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_1_0/LMAC_ETH_1G_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_c_counter_binary_1_0/LMAC_ETH_1G_c_counter_binary_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_1_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_1_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_1_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_1_0/LMAC_ETH_1G_ila_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_2_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_2_0/LMAC_ETH_1G_ila_2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_ds_0/LMAC_ETH_1G_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_ds_0/LMAC_ETH_1G_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_ds_0/LMAC_ETH_1G_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_pc_0/LMAC_ETH_1G_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/LMAC_ETH_1G_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/CONSTRAINTS/LMAC_ETH_1G.xdc
set_property used_in_implementation false [get_files /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/CONSTRAINTS/LMAC_ETH_1G.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top LMAC_ETH_1G_wrapper -part xczu15eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LMAC_ETH_1G_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LMAC_ETH_1G_wrapper_utilization_synth.rpt -pb LMAC_ETH_1G_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
