# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RX_DFIFO_BCNT || ORIG_REF_NAME==RX_DFIFO_BCNT} -quiet] -quiet

# IP: ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TX_DFIFO_BCNT || ORIG_REF_NAME==TX_DFIFO_BCNT} -quiet] -quiet

# IP: ip/TX_DFIFO_1/TX_DFIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TX_DFIFO || ORIG_REF_NAME==TX_DFIFO} -quiet] -quiet
