# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu15eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.cache/wt [current_project]
set_property parent.project_path /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/DFIFO_BRIDGE/DFIFO_BRIDGE_RX.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/DFIFO_BRIDGE/DFIFO_BRIDGE_TX.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/LMAC_CORE_TOP.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_SYNTH/LMAC_SYNTH.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/br_sfifo4x32.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/bsh32_dn_88.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/bsh8_dn_64.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/byte_reordering.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/crc32_d16s.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/crc32_d24s.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/crc32_d64.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/crc32_d8s.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/eth_crc32_gen.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo4Kx64.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo4Kx8.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo512x64_2clk.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/fmac_register_if_LE2.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/g2x_ctrl.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gige_crc32x64.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gige_rx.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gige_s2p.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gige_tx_encap.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gige_tx_gmii.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gigerx_bcnt_fifo256x16.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gigerx_fifo256x64_2clk.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/gigerx_fifo256x8.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/rx_decap_LE2.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/rx_xgmii_LE2.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/tcore_fmac_core_LE2.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_CORE_TOP/txfifo_1024x64.v
  /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_RTL/LMAC_DFIFO_TOP.v
}
read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_1/TX_DFIFO.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_1/TX_DFIFO.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_1/TX_DFIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_1/TX_DFIFO_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64_ooc.xdc]

read_ip -quiet /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO/RX_DFIFO.xci
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO/RX_DFIFO.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO/RX_DFIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE_IP/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO/RX_DFIFO_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top LMAC_DFIFO_TOP -part xczu15eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LMAC_DFIFO_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LMAC_DFIFO_TOP_utilization_synth.rpt -pb LMAC_DFIFO_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
