#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : LMAC_ETH_1G.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Apr 08 15:02:47 PDT 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: LMAC_ETH_1G.sh [-help]
# usage: LMAC_ETH_1G.sh [-lib_map_path]
# usage: LMAC_ETH_1G.sh [-noclean_files]
# usage: LMAC_ETH_1G.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'LMAC_ETH_1G.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 zynq_ultra_ps_e_vip_v1_0_3 lib_pkg_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_19 axi_sg_v4_1_10 axi_dma_v7_1_18 xlconstant_v1_1_5 proc_sys_reset_v5_0_12 gtwizard_ultrascale_v1_7_4 gig_ethernet_pcs_pma_v16_1_4 xbip_utils_v3_0_9 c_reg_fd_v12_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_5 xbip_dsp48_addsub_v3_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 c_gate_bit_v12_0_5 xbip_counter_v3_0_5 c_counter_binary_v12_0_12 xlslice_v1_0_1 xlconcat_v2_1_1 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_16 axi_register_slice_v2_1_17 axi_protocol_converter_v2_1_17 axi_clock_converter_v2_1_16 blk_mem_gen_v8_4_1 axi_dwidth_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "LMAC_ETH_1G.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_zynq_ultra_ps_e_0_0/sim/LMAC_ETH_1G_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6e5f/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_18 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6bfe/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_dma_0_1/sim/LMAC_ETH_1G_axi_dma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/sim/bd_b2d9.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_10/sim/bd_b2d9_s00a2s_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_19/sim/bd_b2d9_s01a2s_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_25/sim/bd_b2d9_s02a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_29/sim/bd_b2d9_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_35/sim/bd_b2d9_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_30/sim/bd_b2d9_m00arn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_31/sim/bd_b2d9_m00rn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_32/sim/bd_b2d9_m00awn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_33/sim/bd_b2d9_m00wn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_34/sim/bd_b2d9_m00bn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_26/sim/bd_b2d9_sawn_1.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_27/sim/bd_b2d9_swn_1.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_28/sim/bd_b2d9_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_22/sim/bd_b2d9_s02mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_23/sim/bd_b2d9_s02tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_24/sim/bd_b2d9_s02sic_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_20/sim/bd_b2d9_sarn_1.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_21/sim/bd_b2d9_srn_1.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_16/sim/bd_b2d9_s01mmu_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_17/sim/bd_b2d9_s01tr_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_18/sim/bd_b2d9_s01sic_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_11/sim/bd_b2d9_sarn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_12/sim/bd_b2d9_srn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_13/sim/bd_b2d9_sawn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_14/sim/bd_b2d9_swn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_15/sim/bd_b2d9_sbn_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_7/sim/bd_b2d9_s00mmu_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_8/sim/bd_b2d9_s00tr_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_9/sim/bd_b2d9_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_2/sim/bd_b2d9_arsw_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_3/sim/bd_b2d9_rsw_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_4/sim/bd_b2d9_awsw_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_5/sim/bd_b2d9_wsw_0.sv" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_6/sim/bd_b2d9_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_0/sim/bd_b2d9_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/bd_0/ip/ip_1/sim/bd_b2d9_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_axi_smc_1/sim/LMAC_ETH_1G_axi_smc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_rst_ps8_0_49M_1/sim/LMAC_ETH_1G_rst_ps8_0_49M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/sim/txdata_fifo256x64_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/sim/txwbcnt_fifo4x32_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/sim/rxdata_fifo256x64_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/sim/rxrbcnt_fifo4x32_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/sim/rxrregif_fifo4x8_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/sim/txwregif_fifo4x8_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/sim/txwregif_fifo4x16_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/sim/txfifo_ip_1024x64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxfifo_ip_4Kx64/sim/rxfifo_ip_4Kx64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/pktctrl_fifo_ip/sim/pktctrl_fifo_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/ipcs_fifo_ip/sim/ipcs_fifo_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/br_sfifo_ip_4x32/sim/br_sfifo_ip_4x32.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x64/sim/gigerx_fifo_ip_256x64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x8/sim/gigerx_fifo_ip_256x8.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/sim/gigerx_bcnt_fifo_ip_256x16.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/sim/rxrregif_fifo4x32_ip.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/AXIS_BRIDGE_TOP.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/LMAC_CORE_TOP.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_SYNTH/LMAC_SYNTH.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/REG_IF_BRIDGE/RIF_IF_BRIDGE.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/axis2fib_rxctrl.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/axis2fib_txctrl.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/br_sfifo4x32.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/bsh32_dn_88.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/bsh8_dn_64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/byte_reordering.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/crc32_d16s.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/crc32_d24s.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/crc32_d64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/crc32_d8s.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/eth_crc32_gen.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/fib2fmac_txctrl.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/fmac2fib_rxctrl.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo4Kx64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo4Kx8.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo512x64_2clk.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/fmac_register_if_LE2.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/g2x_ctrl.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gige_crc32x64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gige_rx.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gige_s2p.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gige_tx_encap.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gige_tx_gmii.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gigerx_bcnt_fifo256x16.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gigerx_fifo256x64_2clk.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/gigerx_fifo256x8.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/rx_decap_LE2.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/rx_xgmii_LE2.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/rxdata_fifo256x64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/rxrbcnt_fifo4x32.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/REG_IF_BRIDGE/rxrregif_fifo4x32.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/REG_IF_BRIDGE/rxrregif_fifo4x8.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/tcore_fmac_core_LE2.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/txdata_fifo256x64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/LMAC_CORE_TOP/txfifo_1024x64.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/txwbcnt_fifo4x32.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/REG_IF_BRIDGE/txwregif_fifo4x16.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_BRIDGE/REG_IF_BRIDGE/txwregif_fifo4x8.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ipshared/e17d/LMAC_RTL/AXIS_LMAC_TOP/AXIS_LMAC_TOP.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/sim/LMAC_ETH_1G_AXIS_LMAC_IP_0_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_0_0/sim/LMAC_ETH_1G_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/sim/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/sim/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/sim/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/ip_0/sim/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_gt.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work gig_ethernet_pcs_pma_v16_1_4 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/494d/hdl/gig_ethernet_pcs_pma_v16_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gig_ethernet_pcs_pma_v16_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/494d/hdl/gig_ethernet_pcs_pma_v16_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_resets.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_clocking.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_support.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_reset_sync.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_sync_block.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/transceiver/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_transceiver.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0_block.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0/synth/LMAC_ETH_1G_gig_ethernet_pcs_pma_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a5f8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/cbdd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ad9e/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0e42/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/7f1a/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/693f/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0952/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/c366/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_c_counter_binary_0_0/sim/LMAC_ETH_1G_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_0_0/sim/LMAC_ETH_1G_xlslice_0_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_0_0/sim/LMAC_ETH_1G_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_0_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_0_0/sim/LMAC_ETH_1G_util_ds_buf_0_0.vhd" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_util_ds_buf_1_0/sim/LMAC_ETH_1G_util_ds_buf_1_0.vhd" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_c_counter_binary_1_0/sim/LMAC_ETH_1G_c_counter_binary_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_1_0/sim/LMAC_ETH_1G_xlslice_1_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_2_0/sim/LMAC_ETH_1G_xlslice_2_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlslice_3_0/sim/LMAC_ETH_1G_xlslice_3_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconcat_0_0/sim/LMAC_ETH_1G_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_1_0/sim/LMAC_ETH_1G_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_2_0/sim/LMAC_ETH_1G_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_3_0/sim/LMAC_ETH_1G_xlconstant_3_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_4_0/sim/LMAC_ETH_1G_xlconstant_4_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_xlconstant_5_0/sim/LMAC_ETH_1G_xlconstant_5_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/sim/LMAC_ETH_1G.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_1_0/sim/LMAC_ETH_1G_ila_1_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_ila_2_0/sim/LMAC_ETH_1G_ila_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e9a5/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/2839/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/e4d1/hdl" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0a8d/hdl/verilog" +incdir+"$ref_dir/../../../../LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ipshared/0000/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_ds_0/sim/LMAC_ETH_1G_auto_ds_0.v" \
    "$ref_dir/../../../bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_auto_pc_0/sim/LMAC_ETH_1G_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.LMAC_ETH_1G xil_defaultlib.glbl -o LMAC_ETH_1G_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./LMAC_ETH_1G_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./LMAC_ETH_1G.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_DMA_CLK/LMAC_ETH_1G.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key LMAC_ETH_1G_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc LMAC_ETH_1G_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./LMAC_ETH_1G.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: LMAC_ETH_1G.sh [-help]\n\
Usage: LMAC_ETH_1G.sh [-lib_map_path]\n\
Usage: LMAC_ETH_1G.sh [-reset_run]\n\
Usage: LMAC_ETH_1G.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
