# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/LMAC_ETH_1G_AXIS_LMAC_IP_0_0.xci
# IP: The module: 'LMAC_ETH_1G_AXIS_LMAC_IP_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txdata_fifo256x64_ip || ORIG_REF_NAME==txdata_fifo256x64_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txwbcnt_fifo4x32_ip || ORIG_REF_NAME==txwbcnt_fifo4x32_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxdata_fifo256x64_ip || ORIG_REF_NAME==rxdata_fifo256x64_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxrbcnt_fifo4x32_ip || ORIG_REF_NAME==rxrbcnt_fifo4x32_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x8_ip || ORIG_REF_NAME==rxrregif_fifo4x8_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txwregif_fifo4x8_ip || ORIG_REF_NAME==txwregif_fifo4x8_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txwregif_fifo4x16_ip || ORIG_REF_NAME==txwregif_fifo4x16_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txfifo_ip_1024x64 || ORIG_REF_NAME==txfifo_ip_1024x64} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxfifo_ip_4Kx64 || ORIG_REF_NAME==rxfifo_ip_4Kx64} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pktctrl_fifo_ip || ORIG_REF_NAME==pktctrl_fifo_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ipcs_fifo_ip || ORIG_REF_NAME==ipcs_fifo_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==br_sfifo_ip_4x32 || ORIG_REF_NAME==br_sfifo_ip_4x32} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x64 || ORIG_REF_NAME==gigerx_fifo_ip_256x64} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x8 || ORIG_REF_NAME==gigerx_fifo_ip_256x8} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gigerx_bcnt_fifo_ip_256x16 || ORIG_REF_NAME==gigerx_bcnt_fifo_ip_256x16} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x32_ip || ORIG_REF_NAME==rxrregif_fifo4x32_ip} -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txdata_fifo256x64_ip || ORIG_REF_NAME==txdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txdata_fifo256x64_ip || ORIG_REF_NAME==txdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwbcnt_fifo4x32_ip || ORIG_REF_NAME==txwbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwbcnt_fifo4x32_ip || ORIG_REF_NAME==txwbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxdata_fifo256x64_ip || ORIG_REF_NAME==rxdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxdata_fifo256x64_ip || ORIG_REF_NAME==rxdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrbcnt_fifo4x32_ip || ORIG_REF_NAME==rxrbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrbcnt_fifo4x32_ip || ORIG_REF_NAME==rxrbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x8_ip || ORIG_REF_NAME==rxrregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x8_ip || ORIG_REF_NAME==rxrregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x8_ip || ORIG_REF_NAME==txwregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x8_ip || ORIG_REF_NAME==txwregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x16_ip || ORIG_REF_NAME==txwregif_fifo4x16_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x16_ip || ORIG_REF_NAME==txwregif_fifo4x16_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txfifo_ip_1024x64 || ORIG_REF_NAME==txfifo_ip_1024x64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxfifo_ip_4Kx64 || ORIG_REF_NAME==rxfifo_ip_4Kx64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pktctrl_fifo_ip || ORIG_REF_NAME==pktctrl_fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ipcs_fifo_ip || ORIG_REF_NAME==ipcs_fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==br_sfifo_ip_4x32 || ORIG_REF_NAME==br_sfifo_ip_4x32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x64 || ORIG_REF_NAME==gigerx_fifo_ip_256x64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x8 || ORIG_REF_NAME==gigerx_fifo_ip_256x8} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gigerx_bcnt_fifo_ip_256x16 || ORIG_REF_NAME==gigerx_bcnt_fifo_ip_256x16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x32_ip || ORIG_REF_NAME==rxrregif_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x32_ip || ORIG_REF_NAME==rxrregif_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/LMAC_ETH_1G_AXIS_LMAC_IP_0_0.xci
# IP: The module: 'LMAC_ETH_1G_AXIS_LMAC_IP_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txdata_fifo256x64_ip || ORIG_REF_NAME==txdata_fifo256x64_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txwbcnt_fifo4x32_ip || ORIG_REF_NAME==txwbcnt_fifo4x32_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxdata_fifo256x64_ip || ORIG_REF_NAME==rxdata_fifo256x64_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxrbcnt_fifo4x32_ip || ORIG_REF_NAME==rxrbcnt_fifo4x32_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x8_ip || ORIG_REF_NAME==rxrregif_fifo4x8_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txwregif_fifo4x8_ip || ORIG_REF_NAME==txwregif_fifo4x8_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txwregif_fifo4x16_ip || ORIG_REF_NAME==txwregif_fifo4x16_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==txfifo_ip_1024x64 || ORIG_REF_NAME==txfifo_ip_1024x64} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxfifo_ip_4Kx64 || ORIG_REF_NAME==rxfifo_ip_4Kx64} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pktctrl_fifo_ip || ORIG_REF_NAME==pktctrl_fifo_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ipcs_fifo_ip || ORIG_REF_NAME==ipcs_fifo_ip} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==br_sfifo_ip_4x32 || ORIG_REF_NAME==br_sfifo_ip_4x32} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x64 || ORIG_REF_NAME==gigerx_fifo_ip_256x64} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x8 || ORIG_REF_NAME==gigerx_fifo_ip_256x8} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gigerx_bcnt_fifo_ip_256x16 || ORIG_REF_NAME==gigerx_bcnt_fifo_ip_256x16} -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x32_ip || ORIG_REF_NAME==rxrregif_fifo4x32_ip} -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txdata_fifo256x64_ip || ORIG_REF_NAME==txdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txdata_fifo256x64_ip/txdata_fifo256x64_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txdata_fifo256x64_ip || ORIG_REF_NAME==txdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwbcnt_fifo4x32_ip || ORIG_REF_NAME==txwbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwbcnt_fifo4x32_ip/txwbcnt_fifo4x32_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwbcnt_fifo4x32_ip || ORIG_REF_NAME==txwbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxdata_fifo256x64_ip || ORIG_REF_NAME==rxdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxdata_fifo256x64_ip/rxdata_fifo256x64_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxdata_fifo256x64_ip || ORIG_REF_NAME==rxdata_fifo256x64_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrbcnt_fifo4x32_ip || ORIG_REF_NAME==rxrbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrbcnt_fifo4x32_ip/rxrbcnt_fifo4x32_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrbcnt_fifo4x32_ip || ORIG_REF_NAME==rxrbcnt_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x8_ip || ORIG_REF_NAME==rxrregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x8_ip/rxrregif_fifo4x8_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x8_ip || ORIG_REF_NAME==rxrregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x8_ip || ORIG_REF_NAME==txwregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x8_ip/txwregif_fifo4x8_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x8_ip || ORIG_REF_NAME==txwregif_fifo4x8_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x16_ip || ORIG_REF_NAME==txwregif_fifo4x16_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txwregif_fifo4x16_ip/txwregif_fifo4x16_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txwregif_fifo4x16_ip || ORIG_REF_NAME==txwregif_fifo4x16_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==txfifo_ip_1024x64 || ORIG_REF_NAME==txfifo_ip_1024x64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxfifo_ip_4Kx64 || ORIG_REF_NAME==rxfifo_ip_4Kx64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pktctrl_fifo_ip || ORIG_REF_NAME==pktctrl_fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ipcs_fifo_ip || ORIG_REF_NAME==ipcs_fifo_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==br_sfifo_ip_4x32 || ORIG_REF_NAME==br_sfifo_ip_4x32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x64 || ORIG_REF_NAME==gigerx_fifo_ip_256x64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gigerx_fifo_ip_256x8 || ORIG_REF_NAME==gigerx_fifo_ip_256x8} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gigerx_bcnt_fifo_ip_256x16 || ORIG_REF_NAME==gigerx_bcnt_fifo_ip_256x16} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x32_ip || ORIG_REF_NAME==rxrregif_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G_xczu9eg/LMAC_ETH_1G.srcs/sources_1/bd/LMAC_ETH_1G/ip/LMAC_ETH_1G_AXIS_LMAC_IP_0_0/AXIS_LMAC_IP.srcs/sources_1/ip/rxrregif_fifo4x32_ip/rxrregif_fifo4x32_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rxrregif_fifo4x32_ip || ORIG_REF_NAME==rxrregif_fifo4x32_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
