# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G/AXIS_LMAC_IP/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xci
# IP: The module: 'txfifo_ip_1024x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G/AXIS_LMAC_IP/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'txfifo_ip_1024x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G/AXIS_LMAC_IP/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'txfifo_ip_1024x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G/AXIS_LMAC_IP/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xci
# IP: The module: 'txfifo_ip_1024x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G/AXIS_LMAC_IP/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'txfifo_ip_1024x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/LMAC_ETH_1G/AXIS_LMAC_IP/AXIS_LMAC_IP.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'txfifo_ip_1024x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
