# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
# IP: The module: 'gigerx_fifo_ip_256x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
# IP: The module: 'gigerx_fifo_ip_256x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lewiz/sambashare/KIRATEY/LMAC_DFIFO_BRIDGE/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
