# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/CONSTRAINTS/ps_emio_eth_1g.xdc

# Block Designs: bd/ps_emio_eth_1g/ps_emio_eth_1g.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g || ORIG_REF_NAME==ps_emio_eth_1g} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_c_counter_binary_0_0/ps_emio_eth_1g_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_c_counter_binary_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlslice_0_0/ps_emio_eth_1g_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlslice_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlslice_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlslice_1_0/ps_emio_eth_1g_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlslice_1_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlslice_1_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlslice_2_0/ps_emio_eth_1g_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlslice_2_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlslice_2_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_zynq_ultra_ps_e_0_0/ps_emio_eth_1g_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_0_0/ps_emio_eth_1g_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_1_0/ps_emio_eth_1g_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_1_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_1_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_2_0/ps_emio_eth_1g_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_2_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_2_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_3_0/ps_emio_eth_1g_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_3_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_3_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_4_0/ps_emio_eth_1g_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_4_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_4_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_5_0/ps_emio_eth_1g_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_5_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_5_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_dma_0_0/ps_emio_eth_1g_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_axi_dma_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_axi_dma_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/ps_emio_eth_1g_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_axi_smc_0 || ORIG_REF_NAME==ps_emio_eth_1g_axi_smc_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_rst_ps8_0_49M_0/ps_emio_eth_1g_rst_ps8_0_49M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_rst_ps8_0_49M_0 || ORIG_REF_NAME==ps_emio_eth_1g_rst_ps8_0_49M_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_ps8_0_axi_periph_0/ps_emio_eth_1g_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_ps8_0_axi_periph_0 || ORIG_REF_NAME==ps_emio_eth_1g_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconcat_0_0/ps_emio_eth_1g_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconcat_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_xlconcat_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/ps_emio_eth_1g_AXIS_LMAC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_AXIS_LMAC_0_1 || ORIG_REF_NAME==ps_emio_eth_1g_AXIS_LMAC_0_1} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlconstant_0_2/ps_emio_eth_1g_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlconstant_0_2 || ORIG_REF_NAME==ps_emio_eth_1g_xlconstant_0_2} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_ila_0_0/ps_emio_eth_1g_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_ila_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_ila_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_0_0/ps_emio_eth_1g_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_util_ds_buf_0_0 || ORIG_REF_NAME==ps_emio_eth_1g_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_1_0/ps_emio_eth_1g_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_util_ds_buf_1_0 || ORIG_REF_NAME==ps_emio_eth_1g_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_c_counter_binary_0_1/ps_emio_eth_1g_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_c_counter_binary_0_1 || ORIG_REF_NAME==ps_emio_eth_1g_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_xlslice_0_1/ps_emio_eth_1g_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_xlslice_0_1 || ORIG_REF_NAME==ps_emio_eth_1g_xlslice_0_1} -quiet] -quiet

# IP: bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_auto_pc_0/ps_emio_eth_1g_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_emio_eth_1g_auto_pc_0 || ORIG_REF_NAME==ps_emio_eth_1g_auto_pc_0} -quiet] -quiet

# XDC: bd/ps_emio_eth_1g/ps_emio_eth_1g_ooc.xdc
