# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.cache/wt [current_project]
set_property parent.project_path /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_repo_paths /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/LMAC_DFIFO_BRIDGE_IP [current_project]
set_property ip_output_repo /home/lewiz/sambashare/KIRATEY/runs_ps_emio_eth_1g_lmac_ila/ps_emio_eth_1g.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/hdl/ps_emio_eth_1g_wrapper.v
add_files /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ps_emio_eth_1g.bd
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_c_counter_binary_0_0/ps_emio_eth_1g_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/ip_0/synth/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/ip_0/synth/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/synth/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/synth/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0/synth/ps_emio_eth_1g_gig_ethernet_pcs_pma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_zynq_ultra_ps_e_0_0/ps_emio_eth_1g_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_zynq_ultra_ps_e_0_0/ps_emio_eth_1g_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_dma_0_0/ps_emio_eth_1g_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_dma_0_0/ps_emio_eth_1g_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_dma_0_0/ps_emio_eth_1g_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_10/bd_a288_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_19/bd_a288_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_25/bd_a288_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_29/bd_a288_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_30/bd_a288_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_31/bd_a288_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_32/bd_a288_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_33/bd_a288_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_34/bd_a288_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_26/bd_a288_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_27/bd_a288_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_28/bd_a288_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_20/bd_a288_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_21/bd_a288_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_11/bd_a288_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_12/bd_a288_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_13/bd_a288_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_14/bd_a288_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_15/bd_a288_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_2/bd_a288_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_3/bd_a288_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_4/bd_a288_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_5/bd_a288_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_6/bd_a288_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_1/bd_a288_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/bd_0/ip/ip_1/bd_a288_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_rst_ps8_0_49M_0/ps_emio_eth_1g_rst_ps8_0_49M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_rst_ps8_0_49M_0/ps_emio_eth_1g_rst_ps8_0_49M_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_rst_ps8_0_49M_0/ps_emio_eth_1g_rst_ps8_0_49M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/pktctrl_fifo_ip/pktctrl_fifo_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/ipcs_fifo_ip/ipcs_fifo_ip.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/br_sfifo_ip_4x32/br_sfifo_ip_4x32.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_fifo_ip_256x8/gigerx_fifo_ip_256x8.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/gigerx_bcnt_fifo_ip_256x16/gigerx_bcnt_fifo_ip_256x16.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/txfifo_ip_1024x64/txfifo_ip_1024x64.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO/RX_DFIFO.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO/RX_DFIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/RX_DFIFO_BCNT/RX_DFIFO_BCNT_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_BCNT_1/TX_DFIFO_BCNT_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_1/TX_DFIFO.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_AXIS_LMAC_0_1/LMAC_DFIFO_BRIDGE.srcs/sources_1/ip/TX_DFIFO_1/TX_DFIFO_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_ila_0_0/ps_emio_eth_1g_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_0_0/ps_emio_eth_1g_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_0_0/ps_emio_eth_1g_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_0_0/ps_emio_eth_1g_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_1_0/ps_emio_eth_1g_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_1_0/ps_emio_eth_1g_util_ds_buf_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_util_ds_buf_1_0/ps_emio_eth_1g_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_c_counter_binary_0_1/ps_emio_eth_1g_c_counter_binary_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ip/ps_emio_eth_1g_auto_pc_0/ps_emio_eth_1g_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/ps_emio_eth_1g.srcs/sources_1/bd/ps_emio_eth_1g/ps_emio_eth_1g_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/CONSTRAINTS/ps_emio_eth_1g.xdc
set_property used_in_implementation false [get_files /home/lewiz/sambashare/KIRATEY/RELEASE/runs_lmac_eth_1g_xczu9eg/CONSTRAINTS/ps_emio_eth_1g.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ps_emio_eth_1g_wrapper -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ps_emio_eth_1g_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ps_emio_eth_1g_wrapper_utilization_synth.rpt -pb ps_emio_eth_1g_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
